import { config, tableNames } from '../config.js';
import { putDoc, listDocs, nowIso } from '../storage/repository.js';
import { getEmailClient, getSmsClient } from './client.js';
import { pushStatus, sendPushToMember } from './push.js';
function clean(value){ return String(value || '').trim(); }
function id(){ return `notify_${Date.now()}_${Math.random().toString(36).slice(2,10)}`; }
export async function logNotification(churchId,payload){const row={id:id(),occurredAt:nowIso(),...payload};try{await putDoc(tableNames.notificationLogs,churchId,row.id,row,{channel:row.channel||'',status:row.status||'',recipient:row.recipient||'',eventKey:row.eventKey||'',memberId:row.memberId||'',occurredAt:row.occurredAt});}catch(error){console.error('[NOTIFY][LOG_WRITE_FAILED]',JSON.stringify({churchId,channel:row.channel,status:row.status,eventKey:row.eventKey,error:String(error?.message||error)}));}console.log('[NOTIFY]',JSON.stringify({churchId,channel:row.channel||'',status:row.status||'',recipient:row.recipient||'',memberId:row.memberId||'',eventKey:row.eventKey||'',operationId:row.operationId||'',messageId:row.messageId||'',metadata:row.metadata||{},error:row.error||''}));return row;}
export function communicationStatus(){return {endpointConfigured:Boolean(config.acsEndpoint),email:{enabled:config.acsEmailEnabled,sender:config.acsEmailSender||null},sms:{enabled:config.acsSmsEnabled,fromNumber:config.acsSmsFromNumber||null,inboundProcessing:false},push:pushStatus()};}
export async function lastNotificationResults(churchId,max=20){return (await listDocs(tableNames.notificationLogs,churchId,{max:Math.min(200,max)})).sort((a,b)=>String(b.occurredAt).localeCompare(String(a.occurredAt))).slice(0,max);}
export async function sendEmail({churchId,to,displayName='',subject,text='',html='',eventKey='',memberId='',metadata={}}){const recipient=clean(to);if(!config.acsEmailEnabled)throw new Error('ACS email is disabled');if(!config.acsEmailSender)throw new Error('ACS email sender is not configured');if(!recipient||!recipient.includes('@'))throw new Error('A valid email recipient is required');const message={senderAddress:config.acsEmailSender,recipients:{to:[{address:recipient,displayName:clean(displayName)||undefined}]},content:{subject:clean(subject)||'Church notification',plainText:clean(text)||undefined,html:clean(html)||undefined}};try{const poller=await getEmailClient().beginSend(message);const result=await poller.pollUntilDone();await logNotification(churchId,{channel:'email',status:String(result.status||'submitted'),recipient,operationId:result.id||'',subject:message.content.subject,eventKey,memberId,metadata});return {ok:true,status:result.status||'submitted',id:result.id||null};}catch(error){await logNotification(churchId,{channel:'email',status:'failed',recipient,error:String(error?.message||error).slice(0,500),eventKey,memberId,metadata});throw error;}}
export async function sendSms({churchId,to,message,eventKey='',memberId='',metadata={}}){const recipient=clean(to);if(!config.acsSmsEnabled)throw new Error('ACS SMS is disabled');if(!config.acsSmsFromNumber)throw new Error('ACS SMS sending number is not configured');if(!/^\+[1-9]\d{7,14}$/.test(recipient))throw new Error('SMS recipient must be E.164 format, for example +17135551234');const text=clean(message);if(!text)throw new Error('SMS message is required');try{const results=await getSmsClient().send({from:config.acsSmsFromNumber,to:[recipient],message:text},{enableDeliveryReport:true,tag:'church-scheduler'});const result=results[0];if(!result?.successful)throw new Error(result?.errorMessage||'SMS send failed');await logNotification(churchId,{channel:'sms',status:'submitted',recipient,messageId:result.messageId||'',eventKey,memberId,metadata});return {ok:true,messageId:result.messageId||null};}catch(error){await logNotification(churchId,{channel:'sms',status:'failed',recipient,error:String(error?.message||error).slice(0,500),eventKey,memberId,metadata});throw error;}}

export async function sendPush({churchId,memberId,title,message,eventKey='',metadata={}}){try{const result=await sendPushToMember({churchId,memberId,title,body:message,data:{eventKey,type:metadata?.type||'',...metadata}});const detail={...metadata,successCount:result.successCount,failureCount:result.failureCount,deviceCount:result.deviceCount||0,messageIds:result.messageIds||[],errors:result.errors||[]};if(!result.ok){const error=new Error('Push notification was not delivered to any registered device.');await logNotification(churchId,{channel:'push',status:'failed',recipient:memberId,error:error.message,eventKey,memberId,metadata:detail});error.notificationLogged=true;throw error;}await logNotification(churchId,{channel:'push',status:'submitted',recipient:memberId,eventKey,memberId,metadata:detail});return result;}catch(error){if(!error?.notificationLogged)await logNotification(churchId,{channel:'push',status:'failed',recipient:memberId,error:String(error?.message||error).slice(0,500),eventKey,memberId,metadata});throw error;}}
