import express from 'express';
import crypto from 'node:crypto';
import { requireLogin, requireAdmin } from '../auth/middleware.js';
import { requireModule } from '../modules/registry.js';
import { tableNames } from '../config.js';
import { listDocs, getDoc, putDoc, nowIso } from '../storage/repository.js';
import { appendHistory } from '../scheduler/history.js';

const id=p=>`${p}_${crypto.randomUUID().replace(/-/g,'').slice(0,16)}`;
const clean=(v,n=500)=>String(v||'').trim().slice(0,n);
const dateOk=v=>/^\d{4}-\d{2}-\d{2}$/.test(String(v||''));
export const hubModulesRouter=express.Router();
hubModulesRouter.use(requireLogin);

hubModulesRouter.get('/events',requireModule('events'),async(req,res)=>{const [rows,registrations]=await Promise.all([listDocs(tableNames.events,req.churchId,{max:2000}),listDocs(tableNames.eventRegistrations,req.churchId,{filter:`memberId eq '${String(req.identity.member?.id||'').replace(/'/g,"''")}'`,max:2000})]);const mine=new Map(registrations.map(r=>[r.eventId,r]));res.json(rows.filter(x=>x.active!==false).sort((a,b)=>String(a.dateISO).localeCompare(String(b.dateISO))).map(e=>({...e,myRegistration:mine.get(e.id)||null})));});
hubModulesRouter.post('/events/:id/register',requireModule('events'),async(req,res)=>{const event=await getDoc(tableNames.events,req.churchId,req.params.id);if(!event||event.active===false)return res.status(404).json({error:'Event not found'});const memberId=req.identity.member?.id||'',registrationId=`${event.id}__${memberId}`,existing=await getDoc(tableNames.eventRegistrations,req.churchId,registrationId),status=req.body?.attending===false?'cancelled':'registered',doc={...(existing||{}),id:registrationId,eventId:event.id,memberId,memberName:req.identity.member?.fullName||'',status,partySize:Math.max(1,Math.min(20,Number(req.body?.partySize||1))),notes:clean(req.body?.notes,300),updatedAt:nowIso(),createdAt:existing?.createdAt||nowIso()};await putDoc(tableNames.eventRegistrations,req.churchId,doc.id,doc,{eventId:doc.eventId,memberId,status:doc.status});await appendHistory(req.churchId,{eventType:`event.registration.${status}`,memberId,dateISO:event.dateISO,source:'member',details:{eventId:event.id,partySize:doc.partySize}});res.json({ok:true,registration:doc});});

hubModulesRouter.get('/admin/events',requireAdmin,requireModule('events'),async(req,res)=>{const [events,registrations]=await Promise.all([listDocs(tableNames.events,req.churchId,{max:2000}),listDocs(tableNames.eventRegistrations,req.churchId,{max:10000})]);res.json({events,registrations});});
hubModulesRouter.post('/admin/events',requireAdmin,requireModule('events'),async(req,res)=>{if(!clean(req.body?.titleEn||req.body?.titleEs)||!dateOk(req.body?.dateISO))return res.status(400).json({error:'Event title and valid date are required.'});const eventId=id('event'),doc={id:eventId,titleEn:clean(req.body.titleEn),titleEs:clean(req.body.titleEs),descriptionEn:clean(req.body.descriptionEn,2000),descriptionEs:clean(req.body.descriptionEs,2000),dateISO:req.body.dateISO,startTime:clean(req.body.startTime,5),location:clean(req.body.location),capacity:Math.max(0,Number(req.body.capacity||0)),active:true,createdAt:nowIso(),createdBy:req.identity.member?.id||''};await putDoc(tableNames.events,req.churchId,eventId,doc,{dateISO:doc.dateISO,active:true});res.status(201).json(doc);});
hubModulesRouter.put('/admin/events/:id',requireAdmin,requireModule('events'),async(req,res)=>{const old=await getDoc(tableNames.events,req.churchId,req.params.id);if(!old)return res.status(404).json({error:'Event not found'});const doc={...old,...req.body,id:old.id,updatedAt:nowIso(),updatedBy:req.identity.member?.id||''};await putDoc(tableNames.events,req.churchId,doc.id,doc,{dateISO:doc.dateISO||'',active:doc.active!==false});res.json(doc);});

hubModulesRouter.get('/followups/mine',requireModule('followups'),async(req,res)=>{const memberId=req.identity.member?.id||'';const rows=await listDocs(tableNames.followUps,req.churchId,{filter:`assignedTo eq '${String(memberId).replace(/'/g,"''")}'`,max:1000});res.json(rows.filter(x=>!['cancelled'].includes(x.status)).sort((a,b)=>String(a.dueDate||'9999-12-31').localeCompare(String(b.dueDate||'9999-12-31'))));});
hubModulesRouter.put('/followups/:id',requireModule('followups'),async(req,res)=>{const old=await getDoc(tableNames.followUps,req.churchId,req.params.id);if(!old||old.assignedTo!==req.identity.member?.id)return res.status(404).json({error:'Task not found'});const allowed=['open','in_progress','completed'],status=allowed.includes(req.body?.status)?req.body.status:old.status,doc={...old,status,updatedAt:nowIso(),updatedBy:req.identity.member?.id||''};await putDoc(tableNames.followUps,req.churchId,doc.id,doc,{status:doc.status,assignedTo:doc.assignedTo||'',dueDate:doc.dueDate||''});await appendHistory(req.churchId,{eventType:'followup.member_updated',memberId:req.identity.member?.id||'',source:'member',details:{followUpId:doc.id,status:doc.status}});res.json(doc);});

hubModulesRouter.get('/admin/followups',requireAdmin,requireModule('followups'),async(req,res)=>{const rows=await listDocs(tableNames.followUps,req.churchId,{max:5000});res.json(rows.sort((a,b)=>String(a.dueDate||'').localeCompare(String(b.dueDate||''))));});
hubModulesRouter.post('/admin/followups',requireAdmin,requireModule('followups'),async(req,res)=>{const title=clean(req.body?.title);if(!title)return res.status(400).json({error:'Follow-up title is required.'});const followId=id('followup'),doc={id:followId,title,sourceType:clean(req.body.sourceType,40),sourceId:clean(req.body.sourceId,100),assignedTo:clean(req.body.assignedTo,100),dueDate:dateOk(req.body.dueDate)?req.body.dueDate:'',status:'open',notes:clean(req.body.notes,2000),createdAt:nowIso(),createdBy:req.identity.member?.id||''};await putDoc(tableNames.followUps,req.churchId,followId,doc,{status:doc.status,assignedTo:doc.assignedTo,dueDate:doc.dueDate});await appendHistory(req.churchId,{eventType:'followup.created',memberId:req.identity.member?.id||'',source:'admin',details:{followUpId:followId,sourceType:doc.sourceType,sourceId:doc.sourceId}});res.status(201).json(doc);});
hubModulesRouter.put('/admin/followups/:id',requireAdmin,requireModule('followups'),async(req,res)=>{const old=await getDoc(tableNames.followUps,req.churchId,req.params.id);if(!old)return res.status(404).json({error:'Follow-up not found'});const allowed=['open','in_progress','completed','cancelled'],doc={...old,...req.body,id:old.id,status:allowed.includes(req.body?.status)?req.body.status:old.status,updatedAt:nowIso(),updatedBy:req.identity.member?.id||''};await putDoc(tableNames.followUps,req.churchId,doc.id,doc,{status:doc.status,assignedTo:doc.assignedTo||'',dueDate:doc.dueDate||''});await appendHistory(req.churchId,{eventType:'followup.updated',memberId:req.identity.member?.id||'',source:'admin',details:{followUpId:doc.id,status:doc.status}});res.json(doc);});
