import { tableNames } from '../config.js';
import { listDocs } from '../storage/repository.js';
import { listHistory } from '../scheduler/history.js';
const safe=v=>v==null?'':String(v);
export async function auditRows(churchId,filters={}){const [history,members,services,ministries,assignments]=await Promise.all([listHistory(churchId,{...filters,max:Math.min(Number(filters.max||5000),10000)}),listDocs(tableNames.members,churchId,{max:5000}),listDocs(tableNames.services,churchId,{max:1000}),listDocs(tableNames.ministries,churchId,{max:1000}),listDocs(tableNames.assignments,churchId,{max:10000})]);const mm=new Map(members.map(m=>[m.id,m.fullName])),sm=new Map(services.map(s=>[s.id,s.labelEn||s.labelEs||s.label])),xm=new Map(ministries.map(m=>[m.id,m.labelEn||m.labelEs||m.label])),am=new Map(assignments.map(a=>[a.id,a]));return history.map(h=>{const a=am.get(h.assignmentId)||{};const serviceId=h.serviceId||a.serviceId||String(h.programId||'').split('__')[0]||'';return ({When:h.occurredAt||'',ServiceDate:h.dateISO||'',Event:safe(h.eventType),Who:mm.get(h.memberId)||h.memberId||'System',PreviousMember:mm.get(h.previousMemberId)||h.previousMemberId||'',NewMember:mm.get(h.newMemberId)||h.newMemberId||'',Service:sm.get(serviceId)||serviceId||'',Ministry:xm.get(h.ministryId)||h.ministryId||'',Assignment:h.assignmentId||'',ReplacementRequested:h.eventType==='replacement.requested'?'Yes':'No',CurrentWeekReliabilityAdjustment:h.penaltyEligible===true?'Yes':'No',Source:h.source||'',Reason:h.reason||'',Details:h.details?JSON.stringify(h.details):''});});}
function csvEscape(v){const s=safe(v);return /[",\n]/.test(s)?`"${s.replaceAll('"','""')}"`:s;}
export function toCsv(rows){const headers=Object.keys(rows[0]||{When:'',ServiceDate:'',Event:'',Who:'',PreviousMember:'',NewMember:'',Service:'',Ministry:'',Assignment:'',ReplacementRequested:'',CurrentWeekReliabilityAdjustment:'',Source:'',Reason:'',Details:''});return [headers.join(','),...rows.map(r=>headers.map(h=>csvEscape(r[h])).join(','))].join('\r\n');}
function xmlEsc(v){return safe(v).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;');}
export function toExcelXml(rows){const headers=Object.keys(rows[0]||{When:''});const rowXml=r=>`<Row>${headers.map(h=>`<Cell><Data ss:Type="String">${xmlEsc(r[h])}</Data></Cell>`).join('')}</Row>`;return `<?xml version="1.0"?><Workbook xmlns="urn:schemas-microsoft-com:office:spreadsheet" xmlns:ss="urn:schemas-microsoft-com:office:spreadsheet"><Worksheet ss:Name="Audit Log"><Table><Row>${headers.map(h=>`<Cell><Data ss:Type="String">${xmlEsc(h)}</Data></Cell>`).join('')}</Row>${rows.map(rowXml).join('')}</Table></Worksheet></Workbook>`;}
function pdfEscape(s){return safe(s).replaceAll('\\','\\\\').replaceAll('(','\\(').replaceAll(')','\\)').replace(/[^\x20-\x7E]/g,'?');}
export function toPdf(rows){
  const lines=['Church Scheduler Audit Log','',...rows.flatMap(r=>[`${r.When} | ${r.Event} | ${r.Who}`,`Date: ${r.ServiceDate} | Service: ${r.Service} | Ministry: ${r.Ministry}`,`Previous: ${r.PreviousMember} | New: ${r.NewMember} | Replacement: ${r.ReplacementRequested} | Reliability adj: ${r.CurrentWeekReliabilityAdjustment}`,`Source: ${r.Source} | Reason: ${r.Reason}`,''])];
  const pages=[];for(let i=0;i<lines.length;i+=46)pages.push(lines.slice(i,i+46));
  const objs=[];const pageObjNums=[],contentObjNums=[];const fontObjNum=3+pages.length*2;
  objs[1]='<< /Type /Catalog /Pages 2 0 R >>';
  for(let i=0;i<pages.length;i++){pageObjNums.push(3+i*2);contentObjNums.push(4+i*2);}
  objs[2]=`<< /Type /Pages /Kids [${pageObjNums.map(n=>`${n} 0 R`).join(' ')}] /Count ${pages.length} >>`;
  pages.forEach((page,i)=>{let content='BT /F1 8 Tf 36 575 Td ';for(let j=0;j<page.length;j++){if(j)content+='0 -11 Td ';content+=`(${pdfEscape(page[j]).slice(0,190)}) Tj `;}content+='ET';objs[pageObjNums[i]]=`<< /Type /Page /Parent 2 0 R /MediaBox [0 0 792 612] /Resources << /Font << /F1 ${fontObjNum} 0 R >> >> /Contents ${contentObjNums[i]} 0 R >>`;objs[contentObjNums[i]]=`<< /Length ${Buffer.byteLength(content)} >>\nstream\n${content}\nendstream`;});
  objs[fontObjNum]='<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>';
  const maxObj=fontObjNum;let out='%PDF-1.4\n',offsets=Array(maxObj+1).fill(0);for(let i=1;i<=maxObj;i++){offsets[i]=Buffer.byteLength(out);out+=`${i} 0 obj\n${objs[i]}\nendobj\n`;}const xref=Buffer.byteLength(out);out+=`xref\n0 ${maxObj+1}\n0000000000 65535 f \n${offsets.slice(1).map(o=>String(o).padStart(10,'0')+' 00000 n ').join('\n')}\ntrailer << /Size ${maxObj+1} /Root 1 0 R >>\nstartxref\n${xref}\n%%EOF`;return Buffer.from(out);
}
