import { tableNames } from '../config.js';
import { listDocs } from '../storage/repository.js';
import { listHistory } from '../scheduler/history.js';
const safe=v=>v==null?'':String(v);
function scoreFor(decision,memberId){const rows=decision?.details?.candidates||[];const hit=rows.find(x=>x.memberId===memberId);return hit?.score?.final??hit?.score?.score??'';}
function assignmentLabel(template,assignmentKey){if(!template||!assignmentKey)return assignmentKey||'';for(const item of template.items||[]){if((item.assignmentKeys||[]).includes(assignmentKey))return item.labelEn||item.labelEs||item.label||assignmentKey;}return assignmentKey;}
export async function auditRows(churchId,filters={}){
  const [history,members,services,ministries,assignments,programs,templates,songs]=await Promise.all([
    listHistory(churchId,{...filters,max:Math.min(Number(filters.max||5000),10000)}),listDocs(tableNames.members,churchId,{max:5000}),listDocs(tableNames.services,churchId,{max:1000}),listDocs(tableNames.ministries,churchId,{max:1000}),listDocs(tableNames.assignments,churchId,{max:10000}),listDocs(tableNames.programs,churchId,{max:5000}),listDocs(tableNames.templates,churchId,{max:1000}),listDocs(tableNames.songs,churchId,{max:5000})]);
  const mm=new Map(members.map(m=>[m.id,m.fullName])),sm=new Map(services.map(s=>[s.id,s.labelEn||s.labelEs||s.label])),xm=new Map(ministries.map(m=>[m.id,m.labelEn||m.labelEs||m.label])),am=new Map(assignments.map(a=>[a.id,a])),pm=new Map(programs.map(p=>[p.id,p])),tm=new Map(templates.map(t=>[t.id,t])),songm=new Map(songs.map(s=>[s.id,`#${s.number||''} ${s.titleEn||s.titleEs||s.title||''}`.trim()]));
  const decisions=new Map();for(const h of history)if(h.eventType==='scheduler.decision')decisions.set(`${h.programId||''}|${h.assignmentKey||''}`,h);
  return history.map(h=>{
    const a=am.get(h.assignmentId)||{};const p=pm.get(h.programId||a.programId)||{};const serviceId=h.serviceId||a.serviceId||p.serviceId||String(h.programId||'').split('__')[0]||'';const tpl=tm.get(p.templateId)||{};const memberId=h.memberId||a.currentMemberId||'';const decision=decisions.get(`${h.programId||a.programId||''}|${h.assignmentKey||a.assignmentKey||''}`);const score=scoreFor(decision,memberId);const songIds=h.details?.songIds||a.songIds||[];
    return ({
      When:h.occurredAt||'',ServiceDate:h.dateISO||a.dateISO||p.dateISO||'',ServiceTime:p.startTime||'',Event:safe(h.eventType),Who:mm.get(memberId)||memberId||'System',
      Service:sm.get(serviceId)||serviceId||'',Assignment:assignmentLabel(tpl,h.assignmentKey||a.assignmentKey||''),AssignmentKey:h.assignmentKey||a.assignmentKey||'',Ministry:xm.get(h.ministryId||a.ministryId)||h.ministryId||a.ministryId||'',
      ParticipationStatus:h.eventType==='assignment.completed'?'Served':(a.status||''),SchedulerScore:score,OriginalMember:mm.get(a.originalMemberId)||a.originalMemberId||'',CurrentMember:mm.get(a.currentMemberId)||a.currentMemberId||'',PreviousMember:mm.get(h.previousMemberId)||h.previousMemberId||'',NewMember:mm.get(h.newMemberId)||h.newMemberId||'',
      ReplacementRequested:h.eventType==='replacement.requested'?'Yes':'No',CurrentWeekReliabilityAdjustment:h.penaltyEligible===true?'Yes':'No',Songs:songIds.map(id=>songm.get(id)||id).join('; '),ProgramId:h.programId||a.programId||'',AssignmentId:h.assignmentId||a.id||'',Source:h.source||'',Reason:h.reason||'',Details:h.details?JSON.stringify(h.details):''
    });
  });
}
function csvEscape(v){const s=safe(v);return /[",\n]/.test(s)?`"${s.replaceAll('"','""')}"`:s;}
export function toCsv(rows){const headers=Object.keys(rows[0]||{When:'',ServiceDate:'',Event:'',Who:''});return [headers.join(','),...rows.map(r=>headers.map(h=>csvEscape(r[h])).join(','))].join('\r\n');}
function xmlEsc(v){return safe(v).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;');}
export function toExcelXml(rows,sheetName='Audit Log'){const headers=Object.keys(rows[0]||{When:''});const rowXml=r=>`<Row>${headers.map(h=>`<Cell><Data ss:Type="String">${xmlEsc(r[h])}</Data></Cell>`).join('')}</Row>`;return `<?xml version="1.0"?><Workbook xmlns="urn:schemas-microsoft-com:office:spreadsheet" xmlns:ss="urn:schemas-microsoft-com:office:spreadsheet"><Worksheet ss:Name="${xmlEsc(sheetName)}"><Table><Row>${headers.map(h=>`<Cell><Data ss:Type="String">${xmlEsc(h)}</Data></Cell>`).join('')}</Row>${rows.map(rowXml).join('')}</Table></Worksheet></Workbook>`;}
function pdfEscape(s){return safe(s).replaceAll('\\','\\\\').replaceAll('(','\\(').replaceAll(')','\\)').replace(/[^\x20-\x7E]/g,'?');}
export function toPdf(rows,{title='Church Scheduler Audit Log'}={}){
  const headers=Object.keys(rows[0]||{});const lines=[title,'',...rows.flatMap(r=>{const preferred=['When','ServiceDate','ServiceTime','Who','Service','Assignment','Ministry','ParticipationStatus','SchedulerScore','PreviousMember','NewMember','ReplacementRequested','CurrentWeekReliabilityAdjustment','Songs','Event','Source','Reason'];const chosen=preferred.some(k=>k in r)?preferred.filter(k=>k in r):headers;const fields=chosen.map(k=>`${k}: ${safe(r[k])}`);return [...fields,''];})];
  const pages=[];for(let i=0;i<lines.length;i+=46)pages.push(lines.slice(i,i+46));if(!pages.length)pages.push([title,'No records']);
  const objs=[];const pageObjNums=[],contentObjNums=[];const fontObjNum=3+pages.length*2;objs[1]='<< /Type /Catalog /Pages 2 0 R >>';for(let i=0;i<pages.length;i++){pageObjNums.push(3+i*2);contentObjNums.push(4+i*2);}objs[2]=`<< /Type /Pages /Kids [${pageObjNums.map(n=>`${n} 0 R`).join(' ')}] /Count ${pages.length} >>`;
  pages.forEach((page,i)=>{let content='BT /F1 8 Tf 36 575 Td ';for(let j=0;j<page.length;j++){if(j)content+='0 -11 Td ';content+=`(${pdfEscape(page[j]).slice(0,190)}) Tj `;}content+='ET';objs[pageObjNums[i]]=`<< /Type /Page /Parent 2 0 R /MediaBox [0 0 792 612] /Resources << /Font << /F1 ${fontObjNum} 0 R >> >> /Contents ${contentObjNums[i]} 0 R >>`;objs[contentObjNums[i]]=`<< /Length ${Buffer.byteLength(content)} >>\nstream\n${content}\nendstream`;});objs[fontObjNum]='<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>';const maxObj=fontObjNum;let out='%PDF-1.4\n',offsets=Array(maxObj+1).fill(0);for(let i=1;i<=maxObj;i++){offsets[i]=Buffer.byteLength(out);out+=`${i} 0 obj\n${objs[i]}\nendobj\n`;}const xref=Buffer.byteLength(out);out+=`xref\n0 ${maxObj+1}\n0000000000 65535 f \n${offsets.slice(1).map(o=>String(o).padStart(10,'0')+' 00000 n ').join('\n')}\ntrailer << /Size ${maxObj+1} /Root 1 0 R >>\nstartxref\n${xref}\n%%EOF`;return Buffer.from(out);
}
