import { inflateRawSync } from 'node:zlib';
const safe=v=>v==null?'':String(v);
export const norm=v=>safe(v).trim().toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9]+/g,' ').trim();
const IDENTITY_HEADERS=new Set(['full name','name','nombre','nombre completo','first name','last name','first name nombre','last name apellido','username','usuario','email','correo','phone','telefono','teléfono','active','activo']);
export function parseCsv(text){
  const rows=[];let row=[],cell='',quoted=false;
  for(let i=0;i<text.length;i++){const ch=text[i];if(quoted){if(ch==='"'&&text[i+1]==='"'){cell+='"';i++;}else if(ch==='"')quoted=false;else cell+=ch;}else if(ch==='"')quoted=true;else if(ch===','){row.push(cell);cell='';}else if(ch==='\n'){row.push(cell.replace(/\r$/,''));rows.push(row);row=[];cell='';}else cell+=ch;}
  if(cell.length||row.length){row.push(cell.replace(/\r$/,''));rows.push(row);}const headers=(rows.shift()||[]).map(x=>String(x||'').trim());return rows.filter(r=>r.some(v=>String(v||'').trim())).map(r=>Object.fromEntries(headers.map((h,i)=>[h,r[i]??''])));
}
export function splitAssignmentHeader(header){const raw=String(header||'').trim();if(!raw||IDENTITY_HEADERS.has(norm(raw)))return null;const parts=raw.split(/\s+-\s+/);if(parts.length<2)return null;const serviceName=parts.shift().trim(),assignmentName=parts.join(' - ').trim();return serviceName&&assignmentName?{serviceName,assignmentName}:null;}
export function inferServiceSchedule(name){const n=norm(name);let weekday=null;const days=[['sunday','domingo',0],['monday','lunes',1],['tuesday','martes',2],['wednesday','miercoles',3],['thursday','jueves',4],['friday','viernes',5],['saturday','sabado',6]];for(const [en,es,d] of days)if(n.includes(en)||n.includes(es)){weekday=d;break;}let startTime='10:00',timeInferred=false;const explicit=n.match(/\b([01]?\d|2[0-3])[: ]([0-5]\d)\b/);if(explicit){startTime=`${String(Number(explicit[1])).padStart(2,'0')}:${explicit[2]}`;timeInferred=true;}else if(/evening|night|noche|vespertino/.test(n)){startTime='18:00';timeInferred=true;}else if(/afternoon|tarde/.test(n)){startTime='15:00';timeInferred=true;}else if(/morning|manana|matutino/.test(n)){startTime='09:00';timeInferred=true;}return {recurrence:{frequency:'weekly',weekday:weekday??0},startTime,scheduleNeedsReview:weekday==null||!timeInferred};}
export function songTemplateRows(){return [{Number:'1','Title Spanish':'Santo, Santo, Santo','Title English':'Holy, Holy, Holy',Active:'Yes'},{Number:'2','Title Spanish':'Sublime Gracia','Title English':'Amazing Grace',Active:'Yes'}];}
export function memberTemplateRows(){return [{'Full Name':'Maria Lopez',Email:'maria@example.com',Phone:'+15551234567',Active:'Yes','Sunday Evening Service - Songs 1':'X','Sunday Evening Service - Songs 2':'','Sunday Evening Service - Sermon':'','Sunday Evening Service - Announcements':'X','Sunday Evening Service - Closing Prayer':''},{'Full Name':'Juan Perez',Email:'',Phone:'',Active:'Yes','Sunday Evening Service - Songs 1':'','Sunday Evening Service - Songs 2':'X','Sunday Evening Service - Sermon':'X','Sunday Evening Service - Announcements':'','Sunday Evening Service - Closing Prayer':'X'}];}


function xmlDecode(s=''){return String(s).replace(/&lt;/g,'<').replace(/&gt;/g,'>').replace(/&quot;/g,'"').replace(/&apos;/g,"'").replace(/&amp;/g,'&');}
function colIndex(ref='A1'){const letters=String(ref).match(/^[A-Z]+/i)?.[0]?.toUpperCase()||'A';let n=0;for(const c of letters)n=n*26+(c.charCodeAt(0)-64);return n-1;}
function zipEntries(buffer){
  const out=new Map();let eocd=-1;for(let i=buffer.length-22;i>=Math.max(0,buffer.length-65557);i--){if(buffer.readUInt32LE(i)===0x06054b50){eocd=i;break;}}if(eocd<0)throw new Error('Invalid XLSX file.');const count=buffer.readUInt16LE(eocd+10),centralOffset=buffer.readUInt32LE(eocd+16);let p=centralOffset;
  for(let i=0;i<count;i++){if(buffer.readUInt32LE(p)!==0x02014b50)break;const method=buffer.readUInt16LE(p+10),compressedSize=buffer.readUInt32LE(p+20),nameLen=buffer.readUInt16LE(p+28),extraLen=buffer.readUInt16LE(p+30),commentLen=buffer.readUInt16LE(p+32),localOffset=buffer.readUInt32LE(p+42),name=buffer.subarray(p+46,p+46+nameLen).toString('utf8');if(buffer.readUInt32LE(localOffset)!==0x04034b50)throw new Error('Invalid XLSX entry.');const localNameLen=buffer.readUInt16LE(localOffset+26),localExtraLen=buffer.readUInt16LE(localOffset+28),dataStart=localOffset+30+localNameLen+localExtraLen,compressed=buffer.subarray(dataStart,dataStart+compressedSize);let data;if(method===0)data=compressed;else if(method===8)data=inflateRawSync(compressed);else throw new Error('Unsupported XLSX compression.');out.set(name,data);p+=46+nameLen+extraLen+commentLen;}
  return out;
}
export function parseXlsx(buffer){
  const entries=zipEntries(buffer);const sharedXml=entries.get('xl/sharedStrings.xml')?.toString('utf8')||'';const shared=[];for(const m of sharedXml.matchAll(/<si\b[^>]*>([\s\S]*?)<\/si>/g)){const parts=[...m[1].matchAll(/<t\b[^>]*>([\s\S]*?)<\/t>/g)].map(x=>xmlDecode(x[1]));shared.push(parts.join(''));}
  let sheetPath='xl/worksheets/sheet1.xml';const workbook=entries.get('xl/workbook.xml')?.toString('utf8')||'',rels=entries.get('xl/_rels/workbook.xml.rels')?.toString('utf8')||'';const rid=workbook.match(/<sheet\b[^>]*r:id="([^"]+)"/)?.[1];if(rid){const relRe=new RegExp(`<Relationship\\b[^>]*Id="${rid.replace(/[.*+?^${}()|[\\]\\]/g,'\\$&')}"[^>]*Target="([^"]+)"`);const target=rels.match(relRe)?.[1];if(target)sheetPath=target.startsWith('/')?target.slice(1):`xl/${target.replace(/^\.\//,'')}`.replace('xl/xl/','xl/');}
  const sheet=entries.get(sheetPath)||entries.get('xl/worksheets/sheet1.xml');if(!sheet)throw new Error('The Excel workbook does not contain a readable first worksheet.');const xml=sheet.toString('utf8'),matrix=[];
  for(const rm of xml.matchAll(/<row\b[^>]*>([\s\S]*?)<\/row>/g)){const row=[];for(const cm of rm[1].matchAll(/<c\b([^>]*)>([\s\S]*?)<\/c>/g)){const attrs=cm[1],body=cm[2],ref=attrs.match(/\br="([A-Z]+\d+)"/)?.[1]||'',type=attrs.match(/\bt="([^"]+)"/)?.[1]||'',idx=colIndex(ref);let value='';if(type==='inlineStr')value=xmlDecode(body.match(/<t\b[^>]*>([\s\S]*?)<\/t>/)?.[1]||'');else{const raw=body.match(/<v>([\s\S]*?)<\/v>/)?.[1]||'';value=type==='s'?shared[Number(raw)]??'':xmlDecode(raw);}row[idx]=value;}matrix.push(row);}
  const headers=(matrix.shift()||[]).map(v=>safe(v).trim());return matrix.filter(r=>r.some(v=>safe(v).trim())).map(r=>Object.fromEntries(headers.map((h,i)=>[h,r[i]??''])));
}
export function parseSpreadsheetXml(text){
  const rows=[];for(const rm of String(text).matchAll(/<Row\b[^>]*>([\s\S]*?)<\/Row>/gi)){const row=[];for(const cm of rm[1].matchAll(/<Cell\b([^>]*)>([\s\S]*?)<\/Cell>/gi)){const idxAttr=cm[1].match(/ss:Index="(\d+)"/i)?.[1];let idx=idxAttr?Number(idxAttr)-1:row.length;while(row.length<idx)row.push('');const value=xmlDecode(cm[2].match(/<Data\b[^>]*>([\s\S]*?)<\/Data>/i)?.[1]||'');row[idx]=value;}rows.push(row);}const headers=(rows.shift()||[]).map(v=>safe(v).trim());return rows.filter(r=>r.some(v=>safe(v).trim())).map(r=>Object.fromEntries(headers.map((h,i)=>[h,r[i]??''])));
}
