import crypto from 'node:crypto';
import { config, tableNames } from '../config.js';
import { putDoc, nowIso, uploadBuffer } from '../storage/repository.js';
import { enqueueAnnouncement } from '../communications/notifications.js';

function signatureOk(contentType,buf){if(contentType==='application/pdf')return buf.subarray(0,5).toString()==='%PDF-';if(contentType==='image/jpeg')return buf[0]===0xff&&buf[1]===0xd8&&buf[2]===0xff;if(contentType==='image/png')return buf.subarray(0,8).equals(Buffer.from([137,80,78,71,13,10,26,10]));return false;}
export async function createPublication(churchId,input={},actorId=''){
  const id=input.id||`content_${crypto.randomUUID().replace(/-/g,'').slice(0,12)}`;
  const doc={id,kind:String(input.kind||'announcement'),title:String(input.titleEs||input.title||input.titleEn||'').trim(),titleEs:String(input.titleEs||input.title||'').trim(),titleEn:String(input.titleEn||input.title||'').trim(),body:String(input.bodyEs||input.body||input.bodyEn||'').trim(),bodyEs:String(input.bodyEs||input.body||'').trim(),bodyEn:String(input.bodyEn||input.body||'').trim(),address:String(input.address||'').trim(),eventDate:String(input.eventDate||input.dateISO||'').trim(),startTime:String(input.startTime||'').trim().slice(0,5),category:String(input.category||'').trim().slice(0,80),tags:Array.isArray(input.tags)?input.tags.map(x=>String(x).trim()).filter(Boolean).slice(0,20):[],published:input.published!==false,publishedAt:nowIso(),createdAt:nowIso(),createdBy:actorId||''};
  if(input.file?.base64){const contentType=String(input.file.contentType||'application/octet-stream').toLowerCase();if(!['application/pdf','image/jpeg','image/png'].includes(contentType))throw Object.assign(new Error('Attachments must be PDF, JPG/JPEG, or PNG.'),{statusCode:400,code:'INVALID_ATTACHMENT_TYPE'});const raw=String(input.file.base64).replace(/^data:[^;]+;base64,/,'');const buf=Buffer.from(raw,'base64');if(buf.length>8*1024*1024)throw Object.assign(new Error('Attachment must be 8 MB or smaller.'),{statusCode:413,code:'ATTACHMENT_TOO_LARGE'});if(!signatureOk(contentType,buf))throw Object.assign(new Error('Attachment contents do not match the allowed PDF/JPG/PNG type.'),{statusCode:400,code:'INVALID_ATTACHMENT_CONTENT'});const safeName=String(input.file.fileName||'attachment').replace(/[^a-zA-Z0-9._-]/g,'_');const blobName=`${churchId}/${id}/${safeName}`;doc.attachment={...(await uploadBuffer(config.attachmentsContainer,blobName,buf,contentType)),fileName:safeName};}
  await putDoc(tableNames.content,churchId,id,doc,{kind:doc.kind,published:doc.published,publishedAt:doc.publishedAt,eventDate:doc.eventDate||''});if(doc.kind==='announcement'&&doc.published!==false)await enqueueAnnouncement(churchId,doc);return doc;
}
