import { CapabilityRegistry, Risk } from '../../dce/core/capabilityRegistry.js';
const registry=new CapabilityRegistry();
const defs=[
 ['profile.mine','profile','entity.member',Risk.READ,false],['notifications.mine','notifications','entity.notification',Risk.READ,false],
 ['assignments.mine','worship','entity.assignment',Risk.READ,false],['program.query','worship','entity.program',Risk.READ,false],['program.participation','worship','entity.assignment',Risk.READ,false],['replacement.request','worship','entity.assignment',Risk.SELF_WRITE,true],['availability.add','worship','entity.member',Risk.SELF_WRITE,true],
 ['songs.search','songs','entity.song',Risk.READ,false],['songs.mine','songs','entity.song',Risk.READ,false],['songs.status','songs','entity.assignment',Risk.READ,false],['songs.history','songs','entity.song',Risk.READ,false],['songs.select','songs','entity.assignment',Risk.SELF_WRITE,true],
 ['bulletins.latest','publications','entity.publication',Risk.READ,false],['announcements.count','publications','entity.publication',Risk.READ,false],['announcements.list','publications','entity.publication',Risk.READ,false],['announcements.query','publications','entity.publication',Risk.READ,false],
 ['events.query','events','entity.event',Risk.READ,false],['events.myRsvp','events','entity.event',Risk.READ,false],['events.register','events','entity.event',Risk.SELF_WRITE,true],['events.cancelRsvp','events','entity.event',Risk.SELF_WRITE,true],['events.dismiss','events','entity.event',Risk.SELF_WRITE,false],
 ['tasks.mine','tasks','entity.task',Risk.READ,false],['tasks.complete','tasks','entity.task',Risk.SELF_WRITE,true],['tasks.cancel','tasks','entity.task',Risk.SELF_WRITE,true],['tasks.dismiss','tasks','entity.task',Risk.SELF_WRITE,false],
 ['prayer.list','prayer','entity.prayer_request',Risk.READ,false],['prayer.mine','prayer','entity.prayer_request',Risk.READ,false],['prayer.create','prayer','entity.prayer_request',Risk.SELF_WRITE,true],['prayer.delete','prayer','entity.prayer_request',Risk.SELF_WRITE,true],
 ['children.status','children','entity.child',Risk.SENSITIVE_READ,false],['children.workerStatus','children','entity.child',Risk.SENSITIVE_READ,false],['children.pickupCode','children','entity.child',Risk.SENSITIVE_READ,false],['children.pickupRequest','children','entity.child',Risk.SELF_WRITE,true],
 ['admin.programStatus','worship','entity.program',Risk.READ,false],['admin.pendingSongs','songs','entity.assignment',Risk.READ,false],['admin.scheduleGenerate','worship','entity.program',Risk.ADMIN_WRITE,true],['admin.programAdminSet','worship','entity.program',Risk.ADMIN_WRITE,true],
 ['admin.memberSearch','members','entity.member',Risk.READ,false],['admin.memberCreate','members','entity.member',Risk.ADMIN_WRITE,true],['admin.memberDelete','members','entity.member',Risk.PRIVILEGED_WRITE,true],['admin.memberEligibilityQuery','members','entity.member',Risk.READ,false],['admin.memberEligibilityUpdate','members','entity.member',Risk.ADMIN_WRITE,true],
 ['admin.visitors.query','visitors','entity.visitor',Risk.SENSITIVE_READ,false],['admin.eventRsvpList','events','entity.event',Risk.SENSITIVE_READ,false],['admin.bulletinUpload','publications','entity.publication',Risk.ADMIN_WRITE,true],['admin.announcementCreate','publications','entity.publication',Risk.ADMIN_WRITE,true],['admin.announcementUpdate','publications','entity.publication',Risk.ADMIN_WRITE,true],['admin.announcementDelete','publications','entity.publication',Risk.ADMIN_WRITE,true],['admin.eventCreate','events','entity.event',Risk.ADMIN_WRITE,true],['admin.eventUpdate','events','entity.event',Risk.ADMIN_WRITE,true],['admin.eventDelete','events','entity.event',Risk.ADMIN_WRITE,true],['admin.taskCreate','tasks','entity.task',Risk.ADMIN_WRITE,true],['admin.taskUpdate','tasks','entity.task',Risk.ADMIN_WRITE,true],['admin.taskDelete','tasks','entity.task',Risk.ADMIN_WRITE,true],['admin.tasks.query','tasks','entity.task',Risk.READ,false],['admin.prayer.list','prayer','entity.prayer_request',Risk.SENSITIVE_READ,false],['admin.childrenStatus','children','entity.child',Risk.SENSITIVE_READ,false],['admin.reports.query','reports','entity.publication',Risk.READ,false],['admin.communications.query','communications','entity.notification',Risk.READ,false],['admin.audit.query','audit','entity.publication',Risk.SENSITIVE_READ,false],['admin.modules.query','modules','entity.module',Risk.READ,false],['admin.moduleToggle','modules','entity.module',Risk.PRIVILEGED_WRITE,true]
];
for(const [id,domain,entity,risk,confirm] of defs)registry.register({id,domain,entity,risk,confirm,labelEs:id,labelEn:id});
export const churchCapabilities=registry;
export function capabilityCoverage(){const items=registry.list();const byDomain={};for(const c of items){byDomain[c.domain]=(byDomain[c.domain]||0)+1;}return {total:items.length,byDomain,write:items.filter(x=>x.risk!==Risk.READ&&x.risk!==Risk.SENSITIVE_READ).length,sensitive:items.filter(x=>x.risk===Risk.SENSITIVE_READ).length};}
