export const config = {
  port: Number(process.env.PORT || 8080),
  nodeEnv: process.env.NODE_ENV || 'development',
  // Dedicated Westbury edition. This deployment is intentionally single-church.
  churchId: 'westbury',
  seedProfile: 'westbury',
  initialOwnerUsername: (process.env.INITIAL_OWNER_USERNAME || 'churchadmin').trim().toLowerCase(),
  bootstrapCode: process.env.BOOTSTRAP_CODE || '',
  storageAccountName: process.env.AZURE_STORAGE_ACCOUNT_NAME || '',
  storageConnectionString: process.env.AZURE_STORAGE_CONNECTION_STRING || '',
  managedIdentityClientId: process.env.AZURE_CLIENT_ID || '',
  attachmentsContainer: process.env.AZURE_BLOB_ATTACHMENTS_CONTAINER || 'attachments',
  importsContainer: process.env.AZURE_BLOB_IMPORTS_CONTAINER || 'imports',
  backupsContainer: process.env.AZURE_BLOB_BACKUPS_CONTAINER || 'backups',
  cookieSecure: String(process.env.COOKIE_SECURE || '').toLowerCase() === 'true' || process.env.NODE_ENV === 'production',
  sessionDays: Number(process.env.SESSION_DAYS || 30),
  defaultTimezone: process.env.DEFAULT_TIMEZONE || 'America/Chicago',
  acsEndpoint: process.env.ACS_ENDPOINT || '',
  acsEmailEnabled: String(process.env.ACS_EMAIL_ENABLED || '').toLowerCase() === 'true',
  acsEmailSender: process.env.ACS_EMAIL_SENDER || '',
  acsSmsEnabled: String(process.env.ACS_SMS_ENABLED || '').toLowerCase() === 'true',
  acsSmsFromNumber: process.env.ACS_SMS_FROM_NUMBER || '',
  publicAppUrl: String(process.env.PUBLIC_APP_URL || '').replace(/\/$/,''),
  firebaseProjectId: process.env.FIREBASE_PROJECT_ID || '',
  firebaseServiceAccountJsonBase64: process.env.FIREBASE_SERVICE_ACCOUNT_JSON_BASE64 || ''
};

export const tableNames = {
  settings: 'Settings',
  users: 'Users',
  sessions: 'Sessions',
  members: 'Members',
  ministries: 'Ministries',
  services: 'Services',
  templates: 'ProgramTemplates',
  programs: 'Programs',
  assignments: 'Assignments',
  history: 'HistoryEvents',
  content: 'Content',
  songs: 'Songs',
  visitorContacts: 'VisitorContacts',
  petitions: 'Petitions',
  pushSubscriptions: 'PushSubscriptions',
  pushDevices: 'PushDevices',
  notificationLogs: 'NotificationLogs',
  notificationQueue: 'NotificationQueue',
  appNotifications: 'AppNotifications',
  children: 'Children',
  childCheckIns: 'ChildCheckIns'
};
